name: Echidna Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Echidna
        uses: crytic/echidna-action@v2
        id: echidna
        with:
          solc-version: 0.8.9
          files: contracts/test/fuzzing/EIPFuzzTest.sol
          contract: EIPFuzzTest
          config: contracts/test/fuzzing/config.yml
          crytic-args: --hardhat-ignore-compile --solc-remaps @openzeppelin/contracts=node_modules/@openzeppelin/contracts

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.echidna.output-file }}
